"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const index_1 = require("../common/src/index");
const utils_1 = require("../common/utils");
const config_1 = require("../common/config");
const props_1 = require("./props");
const { prefix: prefix } = config_1.default, name = `${prefix}-navbar`, SKIP_MENU_RECT_SCENES = [1433, 1434, 1177, 1175], checkSpecialScene = () => { const { scene: t } = wx.getLaunchOptionsSync(); return SKIP_MENU_RECT_SCENES.includes(t); };
let Navbar = class extends index_1.SuperComponent {
    constructor() { super(...arguments), this.externalClasses = [`${prefix}-class`, `${prefix}-class-placeholder`, `${prefix}-class-content`, `${prefix}-class-title`, `${prefix}-class-left`, `${prefix}-class-center`, `${prefix}-class-left-icon`, `${prefix}-class-home-icon`, `${prefix}-class-capsule`, `${prefix}-class-nav-btn`], this.timer = null, this.options = { multipleSlots: !0 }, this.properties = props_1.default, this.observers = { visible(t) { const { animation: e } = this.properties, i = `${name}${t ? "--visible" : "--hide"}`; this.setData({ visibleClass: `${i}${e ? "-animation" : ""}` }), this.timer && clearTimeout(this.timer), e && (this.timer = setTimeout(() => { this.setData({ visibleClass: i }); }, 300)); }, "title,titleMaxLength"() { const { title: t } = this.properties, e = this.properties.titleMaxLength || Number.MAX_SAFE_INTEGER; let i = t.slice(0, e); e < t.length && (i += "..."), this.setData({ showTitle: i }); } }, this.data = { prefix: prefix, classPrefix: name, boxStyle: "", showTitle: "", hideLeft: !1, hideCenter: !1, isSpecialScene: !1, _menuRect: null, _leftRect: null, _boxStyle: {} }, this.methods = { initStyle() { this.getMenuRect(); const { _menuRect: t, _leftRect: e } = this.data; if (!t || !e || !utils_1.systemInfo)
            return; const i = { "--td-navbar-padding-top": `${utils_1.systemInfo.statusBarHeight}px`, "--td-navbar-right": utils_1.systemInfo.windowWidth - t.left + "px", "--td-navbar-left-max-width": `${t.left}px`, "--td-navbar-capsule-height": `${t.height}px`, "--td-navbar-capsule-width": `${t.width}px`, "--td-navbar-height": `${2 * (t.top - utils_1.systemInfo.statusBarHeight) + t.height}px` }; this.calcCenterStyle(e, t, i); }, calcCenterStyle(t, e, i) { const n = Math.max(t.right, utils_1.systemInfo.windowWidth - e.left), s = Object.assign(Object.assign({}, i), { "z-index": this.properties.zIndex, "--td-navbar-center-left": `${n}px`, "--td-navbar-center-width": `${Math.max(e.left - n, 0)}px` }), a = Object.entries(s).map(([t, e]) => `${t}: ${e}`).join("; "); this.setData({ boxStyle: a, _boxStyle: s }); }, getLeftRect() { (0, utils_1.getRect)(this, `.${name}__left`).then(t => { t.right > this.data._leftRect.right && this.calcCenterStyle(t, this.data._menuRect, this.data._boxStyle); }); }, getMenuRect() { if (!this.data.isSpecialScene && wx.getMenuButtonBoundingClientRect) {
            const t = wx.getMenuButtonBoundingClientRect();
            this.setData({ _menuRect: t, _leftRect: { right: utils_1.systemInfo.windowWidth - t.left } });
        } }, onMenuButtonBoundingClientRectWeightChange() { wx.onMenuButtonBoundingClientRectWeightChange && (this.onMenuButtonBoundingClientRectWeightChangeCallback = t => this.queryElements(t), wx.onMenuButtonBoundingClientRectWeightChange(this.onMenuButtonBoundingClientRectWeightChangeCallback)); }, offMenuButtonBoundingClientRectWeightChange() { this.onMenuButtonBoundingClientRectWeightChangeCallback && wx.offMenuButtonBoundingClientRectWeightChange(this.onMenuButtonBoundingClientRectWeightChangeCallback); }, queryElements(t) { Promise.all([(0, utils_1.getRect)(this, `.${this.data.classPrefix}__left`), (0, utils_1.getRect)(this, `.${this.data.classPrefix}__center`)]).then(([e, i]) => { const n = Math.round(e.right), s = Math.round(i.right), a = t.left; this.setData({ hideLeft: n > a, hideCenter: n > a || s > a }); }); }, goBack() { const { delta: t } = this.data, e = this; this.triggerEvent("go-back"), t > 0 && wx.navigateBack({ delta: t, fail(t) { e.triggerEvent("fail", t); }, complete(t) { e.triggerEvent("complete", t); }, success(t) { e.triggerEvent("success", t); } }); } }; }
    attached() { const t = checkSpecialScene(); t && this.setData({ isSpecialScene: t }), this.initStyle(), this.getLeftRect(), this.onMenuButtonBoundingClientRectWeightChange(); }
    detached() { this.offMenuButtonBoundingClientRectWeightChange(); }
};
Navbar = (0, tslib_1.__decorate)([(0, index_1.wxComponent)()], Navbar);
exports.default = Navbar;
